export const PRIVACY_POLICY_HTML = `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>body{background:#0F0F0F;color:#fff;font-family:-apple-system,sans-serif;padding:24px;line-height:1.7;font-size:15px}h1{color:#6C63FF;font-size:26px;margin-bottom:4px}h2{color:#6C63FF;font-size:17px;margin-top:28px;margin-bottom:8px}p,li{color:#cccccc;margin-bottom:10px}ul{padding-left:20px}.sub{color:#888;font-size:13px;margin-bottom:24px}hr{border:none;border-top:1px solid #2A2A2A;margin:24px 0}.footer{text-align:center;color:#888;font-size:12px;font-style:italic;margin-top:32px}strong{color:#fff}a{color:#6C63FF}</style></head><body>
<h1>Savr</h1><p class="sub">Privacy Policy · Effective Date: April 2026</p><hr/>
<p>At Savr, we are committed to protecting your personal information. This policy explains how we collect, use and protect your data.</p>
<h2>1. Information We Collect</h2><ul><li>Email address and password when you register</li><li>Display name and phone number if you provide them</li><li>Expense amounts, categories, notes and dates</li><li>Budget limits and recurring expense settings</li><li>Device type and OS version for support purposes</li><li>Device identifiers used by Google AdMob for advertising</li></ul>
<h2>2. How We Use Your Information</h2><ul><li>Provide and maintain the app and its features</li><li>Sync your data securely using Supabase cloud infrastructure</li><li>Send local notifications such as budget alerts and reminders</li><li>Display advertisements via Google AdMob to keep the app free</li><li>Comply with legal obligations</li></ul>
<h2>3. Advertising</h2><p>Savr displays advertisements powered by <strong>Google AdMob</strong> to keep the app free. By using the app you consent to the display of advertisements.</p><p><strong>We will never sell your personal data</strong> to advertisers. Your financial data is never shared with advertisers.</p><p>Google AdMob may use device identifiers to show relevant ads. You can opt out of personalized ads through your device settings under <strong>Google → Ads → Opt out of Ads Personalization</strong>.</p><p>For more information visit <a href="https://policies.google.com/privacy">Google's Privacy Policy</a>.</p>
<h2>4. Data Sharing</h2><p>We do not sell your personal data. We may share information only with:</p><ul><li>Supabase — stores and manages your data securely on our behalf</li><li>Google AdMob — serves advertisements within the app</li><li>Legal authorities — if required by law or court order</li><li>Business successors — in case of merger or acquisition, with prior notice</li></ul>
<h2>5. Third Party Services</h2><p>Savr uses the following third party services:</p><ul><li><strong>Supabase</strong> — secure cloud database. <a href="https://supabase.com/privacy">Privacy Policy</a></li><li><strong>Google AdMob</strong> — advertisement service. <a href="https://policies.google.com/privacy">Privacy Policy</a></li><li><strong>Google Sign In</strong> — optional authentication. <a href="https://policies.google.com/privacy">Privacy Policy</a></li></ul>
<h2>6. Data Security</h2><p>Your data is protected with encrypted HTTPS transmission and row-level security ensuring only you can access your personal data.</p>
<h2>7. Data Retention</h2><p>We retain your data as long as your account is active. To delete your account contact us at <a href="mailto:007mwnswrangwary@gmail.com">007mwnswrangwary@gmail.com</a>.</p>
<h2>8. Children's Privacy</h2><p>Savr is not intended for users under the age of 13. We do not knowingly collect data from children under 13.</p>
<h2>9. Your Rights</h2><ul><li>Access and download your data using CSV export in the app</li><li>Request correction of inaccurate data</li><li>Request deletion of your account and all associated data</li><li>Opt out of personalized ads via device settings</li></ul>
<h2>10. Changes to This Policy</h2><p>We may update this policy from time to time. We will notify you of any material changes through the app.</p>
<h2>11. Contact Us</h2><p>App: Savr · Developer: Mwnswrang Wary · Email: <a href="mailto:007mwnswrangwary@gmail.com">007mwnswrangwary@gmail.com</a></p>
<hr/><p class="footer">Savr — Track every rupee, every day.</p>
</body></html>`;

export const TERMS_HTML = `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>body{background:#0F0F0F;color:#fff;font-family:-apple-system,sans-serif;padding:24px;line-height:1.7;font-size:15px}h1{color:#6C63FF;font-size:26px;margin-bottom:4px}h2{color:#6C63FF;font-size:17px;margin-top:28px;margin-bottom:8px}p,li{color:#cccccc;margin-bottom:10px}ul{padding-left:20px}.sub{color:#888;font-size:13px;margin-bottom:24px}hr{border:none;border-top:1px solid #2A2A2A;margin:24px 0}.footer{text-align:center;color:#888;font-size:12px;font-style:italic;margin-top:32px}strong{color:#fff}a{color:#6C63FF}</style></head><body>
<h1>Savr</h1><p class="sub">Terms of Service · Effective Date: April 2026</p><hr/>
<p>Welcome to Savr. By downloading or using the app, you agree to these Terms of Service. Please read them carefully.</p>
<h2>1. Acceptance of Terms</h2><p>By accessing or using Savr, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree, please do not use the app.</p>
<h2>2. Description of Service</h2><p>Savr is a personal expense tracking application that allows you to:</p><ul><li>Track daily expenses and income</li><li>Set and monitor monthly budgets</li><li>View spending reports and analytics</li><li>Set up recurring expenses</li><li>Export your data as CSV</li><li>Sync data across devices via secure cloud storage</li></ul>
<h2>3. User Accounts</h2><ul><li>You must provide accurate information when creating an account</li><li>You are responsible for maintaining the security of your account</li><li>You must notify us immediately of any unauthorized use</li><li>You must be at least 13 years old to use Savr</li></ul>
<h2>4. User Data</h2><ul><li>You own all data you enter into Savr</li><li>You can export and delete your data at any time</li><li>We store your data securely using Supabase cloud infrastructure</li></ul>
<h2>5. Acceptable Use</h2><p>You agree not to:</p><ul><li>Use the app for any illegal or unauthorized purpose</li><li>Attempt to gain unauthorized access to our systems</li><li>Reverse engineer or attempt to extract the source code</li><li>Use the app to store or transmit malicious content</li></ul>
<h2>6. Advertising</h2><p>Savr displays advertisements powered by <strong>Google AdMob</strong> to keep the app free. By using Savr you consent to the display of advertisements.</p><p><strong>We will never sell your personal or financial data to advertisers.</strong></p><p>You can opt out of personalized ads in your device settings under <strong>Google → Ads → Opt out of Ads Personalization</strong>.</p>
<h2>7. Third Party Services</h2><p>Savr uses the following third party services:</p><ul><li><strong>Supabase</strong> — <a href="https://supabase.com/terms">Terms</a> · <a href="https://supabase.com/privacy">Privacy</a></li><li><strong>Google AdMob</strong> — <a href="https://policies.google.com/terms">Terms</a> · <a href="https://policies.google.com/privacy">Privacy</a></li><li><strong>Google Sign In</strong> — <a href="https://policies.google.com/terms">Terms</a> · <a href="https://policies.google.com/privacy">Privacy</a></li></ul>
<h2>8. Intellectual Property</h2><p>All content, design, and software in Savr is owned by Mwnswrang Wary. You may not copy, modify, or distribute any part of the app without written permission.</p>
<h2>9. Disclaimer of Warranties</h2><p>Savr is provided "as is" without warranties of any kind. We do not guarantee that the app will be error-free or uninterrupted. The app is for personal financial tracking only and should not be used as professional financial advice.</p>
<h2>10. Limitation of Liability</h2><p>To the maximum extent permitted by law, Savr and its developer shall not be liable for any indirect, incidental, or consequential damages. Our total liability shall not exceed INR 500.</p>
<h2>11. Data Loss</h2><p>We are not responsible for data loss due to technical failures. We recommend using the CSV export feature regularly as a backup.</p>
<h2>12. Termination</h2><ul><li>You may stop using the app and delete your account at any time</li><li>We reserve the right to suspend accounts that violate these terms</li></ul>
<h2>13. Changes to Terms</h2><p>We may update these terms from time to time. We will notify you of material changes through the app.</p>
<h2>14. Governing Law</h2><p>These terms are governed by the laws of India. Disputes are subject to the exclusive jurisdiction of Indian courts.</p>
<h2>15. Contact Us</h2><p>App: Savr · Developer: Mwnswrang Wary · Email: <a href="mailto:007mwnswrangwary@gmail.com">007mwnswrangwary@gmail.com</a></p>
<hr/><p class="footer">Savr — Spend smart, save more.</p>
</body></html>`;